name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Install dependencies
        working-directory: ./my-app
        run: pnpm install --frozen-lockfile --prefer-offline
      
      - name: Run linting
        working-directory: ./my-app
        run: pnpm lint
      
      - name: Build Next.js app
        working-directory: ./my-app
        run: pnpm build
  
  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: myapp:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
